name: Bug Report
description: Report a bug or incorrect behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Describe what's wrong and how to reproduce it.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the bug? What did you expect vs what happened?
      placeholder: "Example: Volume calculation returns negative values for valid polytopes"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can someone reproduce this?
      placeholder: |
        1. Run `cargo test test_volume_simplex`
        2. Observe negative volume in output
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Logs, error messages, related issues, etc.
      placeholder: "See also #123, might be related to QHull integration"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Attribution:** Issues without a footer are from Jörn. Agents add: `*Agent: worktree-name*`
