name: Feature Request
description: Propose a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Describe what you want to add or improve.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the motivation?
      placeholder: "Example: Can't compute capacity for polytopes with >10 facets due to FFI limit"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: |
        Remove hardcoded 10-facet limit in FFI, add timeout parameter instead.
        Profile HK2017 on 11-12 facet polytopes first to set reasonable timeout.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: "Could also implement GraphPruned variant which is faster"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Attribution:** Issues without a footer are from Jörn. Agents add: `*Agent: worktree-name*`
