#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

commit="unknown"
dirty=""

if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  commit="$(git rev-parse --short=12 HEAD)"
  if [[ -n "$(git status --porcelain)" ]]; then
    dirty="-dirty"
  fi
fi

build_date="$(date +%Y-%m-%d)"

cat > version.tex <<EOF
% Auto-generated by scripts/gen-version.sh; do not edit.
\\renewcommand{\\TalkGitCommit}{${commit}${dirty}}
\\renewcommand{\\TalkBuildDate}{${build_date}}
EOF

echo "[gen-version.sh] wrote version.tex (${commit}${dirty}, ${build_date})"

